# Generated by Django 4.2.13 on 2024-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='about',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='position',
            field=models.CharField(max_length=128, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_info',
            field=models.TextField(null=True, verbose_name='short_info'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogtagmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
